config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $routes->connect('/login', ['controller' => 'Members', 'action' => 'login']);
    $routes->connect('/register', ['controller' => 'Members', 'action' => 'register']);
    $routes->connect('/logout', ['controller' => 'Members', 'action' => 'logout']);
    $routes->connect('/dashboard', ['controller' => 'Members', 'action' => 'index']);
    $routes->connect('/my-files', ['controller' => 'Catalogs', 'action' => 'index']);
    $routes->connect('/my-cart', ['controller' => 'Cart', 'action' => 'index']);
    $routes->connect('/new-files', ['controller' => 'Catalogs', 'action' => 'add']);
    $routes->connect('/search', ['controller' => 'Libraries', 'action' => 'index']);
    $routes->connect('/libraries/:title/:id', ['controller' => 'Libraries', 'action' => 'detail'],['pass'=>['title','id']]);
    $routes->connect('/update-my-files/*', ['controller' => 'Catalogs', 'action' => 'edit']);
    $routes->connect('/delete-my-files/*', ['controller' => 'Catalogs', 'action' => 'delete']);

    $routes->connect('/stadmin', ['controller' => 'Pages', 'action' => 'display', 'home','prefix'=>'stadmin']);
    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

Router::prefix('stadmin', function ($routes) {
    // All routes here will be prefixed with `/admin`
    // And have the prefix => admin route element added.
    $routes->fallbacks('DashedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/OrdersTable.php
<?php
namespace App\Model\Table;

use App\Model\Entity\Order;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Orders Model
 */
class OrdersTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        $this->table('orders');
        $this->displayField('no_order');
        $this->primaryKey('id');
        $this->addBehavior('Timestamp');
        $this->addBehavior('AuditStash.AuditLog');
        $this->belongsTo('Members', [
            'foreignKey' => 'member_id'
        ]);
        $this->hasMany('OrderDetails', [
            'foreignKey' => 'order_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->add('id', 'valid', ['rule' => 'numeric'])
            ->allowEmpty('id', 'create');
            
        
        return $validator;
    }
}

src/Controller/CheckoutController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Utility\Text;

class CheckoutController extends AppController
{
    
    public function index()
    {
        $this->loadModel('PaymentMethods');
        $paymentMethods = $this->PaymentMethods->find('list');
        $this->set(compact('paymentMethods'));
        $session = $this->request->session();
        $carts    = $session->read('Cart');
        $countCart = count($carts);
        if($countCart == 0){
            return $this->redirect(['controller'=>false,'action'=>'my-cart']);
        }
        $totalAmount = 0;
        foreach($carts as $key => $catalog){
            if($this->userData['is_colleger'] == true){
                $totalAmount += 0;
            }else{
                $price = ($catalog->type == 1 ? $this->webSettings['Price.Thesis'] : $this->webSettings['Price.PracticalWork']);
                $totalAmount += $price;
            }
        }
        $this->set(compact('totalAmount'));
    }
    
    public function checkoutFinish()
    {
        $this->autoRender = false;
        $this->loadModel('Orders');
        $session = $this->request->session();
        $carts    = $session->read('Cart');
        $countCart = count($carts);
        if($countCart != 0){
            $totalAmount = 0;
            $dataDetail = [];
            foreach($carts as $key => $catalog){
                if($this->userData['is_colleger'] == true){
                    $price = 0;
                    $totalAmount += 0;
                }else{
                    $price = ($catalog->type == 1 ? $this->webSettings['Price.Thesis'] : $this->webSettings['Price.PracticalWork']);
                    $totalAmount += $price;
                }
                $dataDetail[] = [
                    'catalog_id' => $key,
                    'price' => $price
                ];
            }
            $payment_method_id = 0;
            $status = 1;
            if($totalAmount != 0){
                $payment_method_id = $this->request->data['payment_method_id'];
                $status = 0;
            }

            $order = $this->Orders->newEntity();
            $data  = [
                'member_id'  => $this->userData['id'],
                'total_amount' => $totalAmount,
                'payment_method_id' => $payment_method_id,
                'no_order' => rand(1000,99999),
                'unique_id' => Text::uuid(),
                'status' => $status,
                'status_payment'=>$status,
                'is_colleger' => $status,
                'order_details' => $dataDetail
            ];
            $order = $this->Orders->patchEntity($order,$data);
            if($this->Orders->save($order)){
                if($status == 1){
                    $errMsg = 'Your order has been approved. Please check your email to download your file.';
                }else{
                    $errMsg = 'Your order has been send, Please check your email to see your invoice.';
                }
                $this->response->body(json_encode(['errCode'=>0,'errMsg'=>$errMsg]));
            }else{
                $this->response->body(json_encode(['errCode'=>50,'errMsg'=>'Failed, Please try again ']));
            }    
        }else{
            $this->response->body(json_encode(['errCode'=>55,'errMsg'=>'Failed, Your cart is empty please fill your cart ']));
        }
        
    }

}

src/Template/Checkout/index.ctp
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="box">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="box-title">Checkout</h1>
                            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                                <div class="panel panel-default">
                                    <div class="panel-heading" role="tab" id="headingOne">
                                        <h4 class="panel-title">
                                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                                Summary
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                    <div class="panel-body">
                                        <dl class="dl-horizontal">
                                            <dt>Total Amount</dt>
                                            <dd><span class="price"><?=($totalAmount != 0 ? $this->Number->precision($totalAmount,0) : 'Free');?></span></dd>
                                            <dt>Total File</dt>
                                            <dd><?=$countCart;?> File<?($countCart > 1 ? 's' : '');?></dd>
                                        </dl>
                                    </div>
                                    </div>
                                </div>
                                <?php if($totalAmount != 0):?>
                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab" id="headingTwo">
                                            <h4 class="panel-title">
                                                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                                                    Payment Method
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                            <div class="panel-body">
                                                <?php foreach($paymentMethods as $key => $val):?>
                                                    <div class="radio">
                                                        <label>
                                                            <input type="radio" name="payment_method_id" class="payment_method_id" value="<?=$key;?>  ">
                                                            <?=$val;?>
                                                        </label>
                                                    </div>
                                                <?php endforeach;?>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif;?>
                              <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingThree">
                                  <h4 class="panel-title">
                                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                      List Cart
                                    </a>
                                  </h4>
                                </div>
                                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                                  <div class="panel-body">
                                    <div class="table-responsive">
                                        <table class="table table-cart">
                                            <thead>
                                                <tr>
                                                    <th>Cover</th>
                                                    <th>File Name</th>
                                                    <th>Type</th>
                                                    <th>Author</th>
                                                    <th>Price</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach($carts as $key => $catalog):?>
                                                    <tr>
                                                        <td width="100px">
                                                            <?php $image = $this->Utilities->generateUrlImage('catalogs/img/'.$catalog->img_dir,$catalog->img,'square_');?>
                                                            <img src="<?=$image;?>" class="image-cover">
                                                        </td>
                                                        <td>
                                                            <?php $niceUrl = $this->Utilities->inflectorHumanize($catalog->title);?>
                                                            <a href="<?=$this->request->base;?>/libraries/<?=$niceUrl;?>/<?=$catalog->id;?>">
                                                                <?=$catalog->title;?>
                                                            </a>
                                                        </td>
                                                        <td>
                                                            <?=$catalog->member->display_name;?>
                                                        </td>
                                                        <td>
                                                            <?=($catalog->type == 1 ? 'Thesis' : 'Practical Work' );?>
                                                        </td>
                                                        <td>
                                                            <?php if($userAuth == null || $userAuth['is_colleger'] == false):?>
                                                                <span class="price">IDR<?=($catalog->type == 1 ? $this->Number->precision($settings['Price.Thesis'],0) : $this->Number->precision($settings['Price.PracticalWork'],0));?></span>
                                                            <?php else:?>
                                                                <span class="price">FREE</span>
                                                            <?php endif;?>
                                                        </td>
                                                    </tr>
                                                <?php endforeach;?>
                                            </tbody>
                                        </table>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="<?=$this->request->base;?>/my-cart" class="btn btn-default pull-left"><i class="fa fa-shopping-cart"></i> Edit Cart</a>
                            <a href="#" class="btn btn-primary pull-right finishCheckout"><i class="fa fa-check-circle"></i> Finish</a>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>